/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Admin
 */
public class Class extends javax.swing.JInternalFrame {

    /**
     * Creates new form Class
     */
     Connection con =null;
    PreparedStatement pre = null;
    ResultSet rs = null;
    Statement st=null;
    private String acadamicyeaar;
    private String shift;
    private int roomno;
    String a="";
    int b = 0;
    TableModel dataModel = null;
    
    public void tableall(){
    String sql="select * from t05.classinfo";
    try{
        pre=con.prepareStatement(sql);
        rs=pre.executeQuery();
        table.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
           }
    }
    public void inc(){
        try {
            //t1.setEnabled(false);
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/timetable05", "t05", "t05");
         //   String sql="insert into d1.dummy (id,name) values("+Integer.parseInt(t1.getText())+",'"+t2.getText()+"')";
            st=con.createStatement();  
             rs = st.executeQuery("select * from t05.classinfo");
            while(rs.next())
            {
                a=rs.getString(1);
                 
            }
            if( a=="")
            {
                a="C0";
            }
            a=a.substring(1);
       
            b=Integer.parseInt(a);
            b++;
            a=String.valueOf(b);
            a="C".concat(a);
            
            t1.setText(a); 
        } catch (SQLException ex) {
            Logger.getLogger(Class.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public Class() {
        initComponents();
        inc();
        tableall();
        all();
        
       //this.setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        t2 = new javax.swing.JComboBox<>();
        t3 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setClosable(true);
        setTitle("Class");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("CLASS INFORMATION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 250, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("CLASS ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 83, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("ACADAMIC YEAR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("SHIFT");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 83, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("ROOM NO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 20));

        t1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 59, 77, -1));

        t4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 77, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 97, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "ACADAMIC_YEAR", "SHIFT", "ROOM_NO"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 27, 409, 220));

        t2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        t2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT--", "FY", "SY", "TY" }));
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, 30));

        t3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        t3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT--", "SHIFT-I", "SHIFT-II" }));
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 80, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 330, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            //String sql="insert into data (name,address) values(?,?)";
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/timetable05", "t05", "t05");
            String sql="insert into t05.classinfo(id,acadamicyear,shift,roomno) values('"+t1.getText()+"','"+t2.getSelectedItem()+"','"+t3.getSelectedItem()+"','"+t4.getText()+"')";
      
            pre = con.prepareStatement(sql);
        //    pre.setString(1, name);
          //  pre.setString(2, address);
          pre.executeUpdate();
          JOptionPane.showMessageDialog(null, "inserted");
         //    st=con.createStatement();  
           inc();
           tableall();
            //clear();
            
         //   auto();
        }
        catch(SQLException  e){
           e.printStackTrace();
            
            
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        //int selectedRow = table.getSelectedRow();
        try{
             int row = table.getSelectedRow();
             String t = (table.getModel().getValueAt(row, 0).toString());
             String sql="select * from t05.classinfo where id='"+t+"'";
              pre = con .prepareStatement(sql);
              rs = pre.executeQuery();
              if(rs.next())
              {
                  String a1 = rs.getString("id");
                  t1.setText(a1);
                  String a2 = rs.getString("acadamicyear");
                  t2.setSelectedItem(a2);
                  String a3 = rs.getString("shift");
                  t3.setSelectedItem(a3);
                  String a4 = rs.getString("roomno");
                  t4.setText(a4);
              }
        }
        catch(SQLException  e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        try{
            //String sql="insert into data (name,address) values(?,?)";
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/timetable05", "t05", "t05");
            String sql="update  t05.classinfo set acadamicyear ='"+t2.getSelectedItem()+"', shift='"+t3.getSelectedItem()+"',roomno='"+t4.getText()+"' where id='"+t1.getText()+"'";
            pre = con.prepareStatement(sql);
                   pre.executeUpdate();
            JOptionPane.showMessageDialog(null, "updated");
              tableall();
            
        }
        catch(SQLException  e){
            JOptionPane.showMessageDialog(null, e);
            
            
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/timetable05", "t05", "t05");
            String sql="delete from  t05.classinfo where id='"+t1.getText()+"'";
            pre = con.prepareStatement(sql);
       
            pre.executeUpdate();
            JOptionPane.showMessageDialog(null, "deleted");
        }
        catch(SQLException  e){
            JOptionPane.showMessageDialog(null, e);
            
            
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    
    public void all(){
        try{
              con = DriverManager.getConnection("jdbc:derby://localhost:1527/timetable05", "t05", "t05");
              String sql="select * from t05.classinfo";
              pre = con .prepareStatement(sql);
              rs = pre.executeQuery();
            
            
            
        }
        catch(SQLException  e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JComboBox<String> t2;
    private javax.swing.JComboBox<String> t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
