/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Admin
 */
public class workload extends javax.swing.JInternalFrame {

    /**
     * Creates new form workload
     */
     Connection con =null;
    PreparedStatement pre = null;
    ResultSet rs = null;
    Statement st=null;
    private String workloadid;
    private String teachername;
    private String theorysubject;
    private String practicalsubject;
    private int totalworkload;
    String a="";
    int b = 0;
    TableModel dataModel = null;
    
    public void tableall(){
    String sql="select * from t05.workinfo";
    try{
        pre=con.prepareStatement(sql);
        rs=pre.executeQuery();
        table.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
           }
    }
    public void inc(){
        try {

            con = DriverManager.getConnection("jdbc:derby://localhost:1527/timetable05", "t05", "t05");
        
            st=con.createStatement();  
             rs = st.executeQuery("select * from t05.workinfo");
            while(rs.next())
            {
                a=rs.getString(1);
                 
            }
            if(a=="")
            {
                a="W0";
            }
            a=a.substring(1);
       
            b=Integer.parseInt(a);
            b++;
            a=String.valueOf(b);
            a="W".concat(a);
            
            tw1.setText(a); 
        } catch (SQLException ex) {
            Logger.getLogger(workload.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public workload() {
        initComponents();
        inc();
        tableall();
        all();
        selcombo();
        selcombo1();
        selcombo2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tw1 = new javax.swing.JTextField();
        tw4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        tw2 = new javax.swing.JComboBox<>();
        tw3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tw5 = new javax.swing.JComboBox<>();
        tw6 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setTitle("workload");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("WORKLOAD INFORMATION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 11, 207, 28));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("WORKLOAD ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 110, 19));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("TEACHER NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 19));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("THEORY SUBJECT");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 21));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("TOTAL WORKLOAD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 23));

        tw1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tw1ActionPerformed(evt);
            }
        });
        getContentPane().add(tw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 97, 30));
        getContentPane().add(tw4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 98, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 83, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "workload_id", "teacher_name", "subject", "Practical_subject", "BATCH", "total_workload"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 11, 584, 283));

        tw2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT--" }));
        tw2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tw2ActionPerformed(evt);
            }
        });
        getContentPane().add(tw2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 97, 30));

        tw3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT--", "-" }));
        tw3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tw3ActionPerformed(evt);
            }
        });
        getContentPane().add(tw3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 96, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("PRACTICAL SUBJECT");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 21));

        tw5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT--", "-" }));
        tw5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tw5ActionPerformed(evt);
            }
        });
        getContentPane().add(tw5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 98, 30));

        tw6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- SELECT--", "F1", "F2", "F3", "-" }));
        getContentPane().add(tw6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 98, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("BATCH");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 55, 21));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tw2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tw2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tw2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try{
           
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/timetable05", "t05", "t05");
            String sql="insert into t05.workinfo(workloadid,teachername,theorysubject,practicalsubject,batch,totalworkload) values('"+tw1.getText()+"','"+tw2.getSelectedItem()+"','"+tw3.getSelectedItem()+"','"+tw5.getSelectedItem()+"','"+tw6.getSelectedItem()+"','"+tw4.getText()+"')";
      
            pre = con.prepareStatement(sql);
       
          pre.executeUpdate();
          JOptionPane.showMessageDialog(null, "inserted");
         
           inc();
           tableall();
            
        
        }
        catch(SQLException  e){
           e.printStackTrace();
            
            
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tw3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tw3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tw3ActionPerformed

    private void tw5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tw5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tw5ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
         try{
             int row = table.getSelectedRow();
             String t = (table.getModel().getValueAt(row, 0).toString());
             String sql="select * from t05.workinfo where workloadid='"+t+"'";
              pre = con .prepareStatement(sql);
              rs = pre.executeQuery();
              if(rs.next())
              {
                  String a1 = rs.getString("workloadid");
                  tw1.setText(a1);
                  String a2 = rs.getString("teachername");
                  tw2.setSelectedItem(a2);
                  String a3 = rs.getString("theorysubject");
                  tw3.setSelectedItem(a3);
                  String a4 = rs.getString("practicalsubject");
                  tw5.setSelectedItem(a4);
                  String a5 = rs.getString("batch");
                  tw6.setSelectedItem(a5);
                  String a6 = rs.getString("totalworkload");
                  tw4.setText(a6);
              }
        }
        catch(SQLException  e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_tableMouseClicked

    private void tw1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tw1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tw1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{
           
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/timetable05", "t05", "t05");
            String sql="update  t05.workinfo  set teachername='"+tw2.getSelectedItem()+"',theorysubject='"+tw3.getSelectedItem()+"',practicalsubject='"+tw5.getSelectedItem()+"',batch='"+tw6.getSelectedItem()+"',totalworkload='"+tw4.getText()+"' where workloadid='"+tw1.getText()+"'";
            pre = con.prepareStatement(sql);
        
            pre.executeUpdate();
            JOptionPane.showMessageDialog(null, "updated");
              tableall();
        }
        catch(SQLException  e){
            JOptionPane.showMessageDialog(null, e);
            
            
            
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try{
            //String sql="insert into data (name,address) values(?,?)";
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/timetable05", "t05", "t05");
            String sql="delete from  t05.workinfo where workloadid='"+tw1.getText()+"'";
            pre = con.prepareStatement(sql);
        //    pre.setString(1, name);
          //  pre.setString(2, address);
            pre.executeUpdate();
            JOptionPane.showMessageDialog(null, "deleted");
        }
        catch(SQLException  e){
            JOptionPane.showMessageDialog(null, e);
            
            
            
        }
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed
 public void all(){
        try{
              con = DriverManager.getConnection("jdbc:derby://localhost:1527/timetable05", "t05", "t05");
              String sql="select * from t05.workinfo";
              pre = con .prepareStatement(sql);
              rs = pre.executeQuery();
            
            
        }
        catch(SQLException  e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
public void selcombo(){
    try{
        String sql="select teachername from t05.finfo";
        pre = con.prepareStatement(sql);
        rs = pre.executeQuery();
        while(rs.next())
        {
            
            tw2.addItem(rs.getString("teachername"));
        }
    }
        catch(SQLException  e){
            JOptionPane.showMessageDialog(null, e);
        }
}
 public void selcombo1(){
    try{
        String sql="select theorysubject from t05.subinfo"; 
        pre = con.prepareStatement(sql);
        rs = pre.executeQuery();
        while(rs.next())
        {
            
            tw3.addItem(rs.getString("theorysubject"));
        }
    }
        catch(SQLException  e){
            JOptionPane.showMessageDialog(null, e);
        }
}
 public void selcombo2(){
    try{
        String sql="select pracicalsubject from t05.pinfo"; 
        pre = con.prepareStatement(sql);
        rs = pre.executeQuery();
        while(rs.next())
        {
           
            tw5.addItem(rs.getString("pracicalsubject"));
        }
    }
        catch(SQLException  e){
            JOptionPane.showMessageDialog(null, e);
        }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField tw1;
    private javax.swing.JComboBox<String> tw2;
    private javax.swing.JComboBox<String> tw3;
    private javax.swing.JTextField tw4;
    private javax.swing.JComboBox<String> tw5;
    private javax.swing.JComboBox<String> tw6;
    // End of variables declaration//GEN-END:variables
}
